### ISSUE TITLE
Error while calling TeX-next-error from compile-commands-until-done

### ISSUE THREAD

**Issue by roshanshariff** [Bruce-Connor/latex-extra#8]
After running compile-commands-until-done with C-c C-a, if there are errors it prompts you if you want to go to the next one. If you do, then it gives the following error:
TeX-next-error: Wrong type argument: number-or-marker-p, t

Using C-c ` to go to the next error works fine. I assume the t argument to TeX-next-error is meant to be the 'reparse' option, but TeX-next-error takes a raw prefix argument before that for how many errors to jump forward/backward.

I'm running emacs 24.4.1 with auctex 11.88.

**Comment by Bruce-Connor** [comment]
Thanks for filing this.
It's odd that I never ran into this possible, I use this command all the time. 

Might be something specific to AucTeX version.
I'll look into it when I'm home.

**Comment by roshanshariff** [comment]
Looks like it was this commit that added the extra argument (to allow implementing TeX-previous-error): http://git.savannah.gnu.org/cgit/auctex.git/commit/tex-buf.el?id=fb40d4253a9937a325b39ad886ba709d07016c3d

That change was made between auctex 11.87 and 11.88.

**Comment by Bruce-Connor** [comment]
Should be fixed now. Let me know if it still happens for you.

**Comment by roshanshariff** [comment]
That fixes the problem. Thanks!
